import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import authWrapper from "../containers/hoc/authWrapper";

const inter = Inter({ subsets: ["latin"] });

const HomePage = ({ auth }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <div>
          <p>
            Get started by editing&nbsp;
            <code>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
      </main>
    </>
  );
};

// export default HomePage;
export default authWrapper(HomePage);
